#let terms = (
  (slug: "term-action-node", title: [ActionNode], body: [A node adapter for one Jido Action with per-use options.]),
  (slug: "term-agent-node", title: [AgentNode], body: [A node adapter for one Jido Agent with synchronous, asynchronous, or streaming execution configuration.]),
  (slug: "term-human-node", title: [HumanNode], body: [A node that requests human input and immediately yields a suspension outcome.]),
  (slug: "term-dynamic-agent-node", title: [DynamicAgentNode], body: [A node that selects skills from a registry, assembles an orchestrator, and executes the requested task.]),
  (slug: "term-strategy", title: [Strategy], body: [The command-processing behavior that updates an agent value and describes work for its runtime.]),
  (slug: "term-strategy-state", title: [Strategy state], body: [The strategy-owned value stored under the agent state's reserved #raw("__strategy__") key.]),
  (slug: "term-directive", title: [Directive], body: [A description of an external operation emitted for a runtime to execute.]),
  (slug: "term-fan-out-branch", title: [FanOutBranch], body: [A directive describing one child-node execution and its prepared input within a parallel or traverse operation.]),
  (slug: "term-suspend-directive", title: [Suspend directive], body: [A directive carrying suspension metadata, optional notification configuration, and hibernate intent. _Avoid_: suspend outcome — the outcome is a result marker, not a runtime operation.]),
  (slug: "term-suspend-for-human", title: [SuspendForHuman], body: [A compatibility constructor for a suspension directive whose reason is human input.]),
  (slug: "term-checkpoint-and-stop", title: [CheckpointAndStop], body: [A directive requesting durable checkpoint storage, parent notification, and process termination.]),
  (slug: "term-resume", title: [Resume], body: [The addressing operation that delivers a continuation to a live agent or restores a checkpointed agent before delivery.]),
  (slug: "term-llm-action", title: [LLMAction], body: [The Jido Action boundary between an orchestrator and ReqLLM generation and conversation handling.]),
  (slug: "term-agent-tool", title: [AgentTool], body: [The adapter between node metadata and model tool descriptions, arguments, and correlated results.]),
  (slug: "term-obs", title: [Obs], body: [A strategy-specific value tracking observation spans and measurements for one execution.]),
  (slug: "term-otel-ctx", title: [OtelCtx], body: [The boundary for attaching and restoring process-local OpenTelemetry context.]),
  (slug: "term-req-options", title: [Req options], body: [Opaque HTTP configuration forwarded through an orchestrator to ReqLLM's Req integration.]),
  (slug: "term-replay-directives", title: [Replay directives], body: [Operations reconstructed from checkpointed execution state to re-establish interrupted work.]),
)
