#import "../.render/designlib.typ": *
#let title = [Execution]
#let body = [
  #section(title: "Foundation", lead: "Execution connects the shared composition values to Jido agents, runtime directives, model calls, storage, and observations.", body: [
    #goal(title: "Execute the same composition in supported runtimes")[Consumers can drive directive loops directly for tests or use AgentServer for process-based execution.]
    #goal(title: "Resume nested work with preserved logical state")[Checkpointing retains conversation, context, pending decisions, and child tracking while reconstructing runtime-derived fields.]
    #no-goal(title: "Provide a host application or approval transport")[Composer defines notification and resume data but does not supply a user interface, transport, durable scheduler, or authorization service.]
    #no-goal(title: "Add unsupported collection or registry mechanisms")[Custom MapNode reduction, incremental collection output, element-transform callbacks, service discovery, and a Jido AI skill adapter are not part of the migrated scope.]
    #invariant(title: "Every incoming signal has an explicit route", enforcement: "mechanism")[AgentServer rejects unknown signal types; each strategy declares every signal it consumes.]
    #invariant(title: "A completed branch retains its collected result", enforcement: "mechanism")[A sibling suspension does not discard completed parallel results. Merge waits for all required branches to resolve.]
    #principle(title: "Use existing provider and runtime abstractions")[ReqLLM owns provider differences. Jido owns AgentServer, directive execution, signals, and base persistence.]
    #principle(title: "Keep assembly separate from execution")[Skill assembly produces inspectable configuration without running a model loop.]
  ])
    #pending-ledger(
      pending-entry(title: "Settle HumanNode exposure as an LLM tool", kind: "ruling", since: "2026-09-02")[HumanNode.to_tool_spec returns nil and its test explicitly excludes LLM-tool use. The advisory-tool descriptions remain carried intent, not executable support; choosing whether to add that support still needs an owner decision.],
      pending-entry(title: "Normalize approval policy and resume contracts", kind: "ruling", since: "2026-09-02")[The observed policy gates only on the atom require_approval; a tuple with options does not gate. Both strategies use composer.suspend.resume, refuse unmatched resumes, and ignore resolved timeouts. The source's tuple-policy and legacy-response alternatives remain unselected.],
      pending-entry(title: "Qualify the pure-strategy boundary", kind: "ruling", since: "2026-09-02")[The implementation executes termination through Jido.Exec.run inline and emits observation effects from strategy helpers. These exceptions are confirmed; deciding whether to move them behind directives remains open.],
      pending-entry(title: "Require safe checkpoint preparation and parent stripping", kind: "ruling", since: "2026-09-02")[The default agent checkpoint retains #raw("__parent__.pid") and does not invoke Composer preparation or add Composer schema and claim markers. The safe serialization requirement remains intent; automatic preparation and parent-reference cleanup are not implemented guarantees.],
      pending-entry(title: "Choose whether to implement OTP hibernation", kind: "ruling", since: "2026-09-02")[SuspendExec confirms log-only hibernate intent with unchanged state. The source's directive-return or passive AgentServer alternatives remain unselected; checkpoint-and-stop is a separate mechanism.],
      pending-entry(title: "Settle persistence failures and replay safety", kind: "ruling", since: "2026-09-02")[CheckpointAndStop stops and may notify its parent even when persistence is absent or fails. Resume thaws before its optional claim, leaves a failed delivery claim without rollback, and ignores final claim-update failure. These observed limitations do not endorse lost checkpoints or establish exactly-once effects; mixed-wait labels, ChildRef checkpoint-exit handling, and runtime policy restoration also remain owner decisions.],
      pending-entry(title: "Verify carried error and MapNode contracts", kind: "ruling", since: "2026-09-02")[Source intent requires uniform machine-readable error diagnostics and MapNode element-count, concurrency, and completion measurements. Current Error fields vary by class and several paths return ordinary errors; the observation code inspected does not establish the complete MapNode measurement contract. MapNode's direct path also supplies element-only parameters, unlike the full-context directive path; preserve the source's context intent until that difference is ruled.],
    )
  #pagebreak()
  #section(title: "System at a glance", lead: "The consumer API configures strategies. Strategies interpret events and return work for a runtime to perform.", visual: diagram(
    altitude: "L3", title: "Execution components", accent: "blue", flow: "top-to-bottom",
    nodes: ((id: "dsl", label: "Workflow and Orchestrator DSLs"), (id: "strategy", label: "Strategies"), (id: "model", label: "Core model", tint: "teal"), (id: "node", label: "Node adapters"), (id: "runtime", label: "AgentServer or sync driver", external: true), (id: "llm", label: "LLMAction and AgentTool"), (id: "persist", label: "Checkpoint and Resume"), (id: "obs", label: "Obs and OtelCtx")),
    edges: (("dsl", "strategy", "configures"), ("strategy", "model", "updates"), ("strategy", "node", "asks for directives"), ("node", "runtime", "describes work"), ("runtime", "strategy", "returns events"), ("runtime", "llm", "executes"), ("runtime", "persist", "persists or restores"), ("strategy", "obs", "reports")),
    caption: [The core model is a separate documentation context. All blue components belong to execution; the runtime boundary performs actions, child creation, delivery, and persistence. The documented inline termination and observation exceptions are recorded above.],
  ), body: [
    #components(
      component(name: "Consumer interface", mission: "Builds agents and starts or configures runs."),
      component(name: "Node adapters", mission: "Translate configured operations into direct calls or directives."),
      component(name: "Strategies", mission: "Accept results and update workflow or orchestration progress."),
      component(name: "Suspension and persistence", mission: "Retain pending work and restore addressable continuations."),
      component(name: "Observation and testing", mission: "Expose execution evidence and test each boundary."),
    )
    #points([#ctx("execution") uses #ctx("core-model") as the supplier of shared contracts. Within execution, integration concerns remain sections rather than new bounded contexts.])
  ])
  #pagebreak()
  #section(title: "Consumer interface", lead: "Both DSLs produce standard Jido Agent modules. Module names and descriptions become the metadata visible to a parent composition.", body: [
    #md-table(3, ([Entry point], [Result], [Purpose], [Workflow.new], [Agent], [Initialize configured strategy state], [Workflow.run(agent, context)], [Agent and directives], [Start a workflow without executing its effects], [Workflow.run_sync(agent, context)], [ok with context or error with reason], [Drive to a terminal state for scripts and tests], [Orchestrator.new], [Agent], [Initialize orchestration state], [Orchestrator.query(agent, query, context)], [Agent and directives], [Start a model-directed run], [Orchestrator.query_sync(agent, query, context)], [ok with agent and result; suspended with agent and suspension; or error], [Drive a synchronous query], [Orchestrator.configure(agent, overrides)], [Agent], [Apply runtime configuration before query]))
    #code-block("elixir", "Workflow.run(agent, context) -> {agent, directives}\nWorkflow.run_sync(agent, context) -> {:ok, result_context} | {:error, reason}\nOrchestrator.query(agent, query, context) -> {agent, directives}\nOrchestrator.query_sync(agent, query, context) ->\n  {:ok, agent, result} | {:suspended, agent, suspension} | {:error, reason}")
    #points([Synchronous drivers are intended for scripts and tests, not to block inside AgentServer. Runtime composition uses directives and lifecycle signals.], [get_action_modules reads the currently configured modules; get_termination_module returns the configured termination action or nil.], [Jido.Composer is the namespace and documentation entry point, not a separate business-logic coordinator.])
    #subsection(title: "Workflow configuration")[
      A workflow declares state bindings and an outcome-driven transition graph.
      #md-table(2, ([Option], [Contract], [name and description], [Agent identity and parent-visible description], [schema], [Agent state schema; defaults to an empty list and passes to Jido.Agent], [nodes], [State atom to node specification], [transitions], [State-outcome pair to next-state atom], [initial], [Initial nonterminal state], [terminal_states and success_states], [Both absent or both supplied; successful states form a subset], [ambient], [Input keys protected as ambient], [fork_fns], [Named MFA transformations at child boundaries]))
      #md-table(2, ([Node specification], [Interpretation], [#raw("ActionModule")], [ActionNode with defaults], [#raw("{ActionModule, opts}")], [ActionNode with per-use options], [#raw("{AgentModule, mode: :sync}")], [AgentNode with explicit mode], [#raw("%FanOutNode{...}")], [Explicit configured node struct]))
      #points([Plain Action modules are wrapped as ActionNode; Agent modules are wrapped as AgentNode. Explicit node structs retain per-instance configuration.], [The compiler rejects missing initial nodes, invalid referenced nonterminal states, and invalid terminal/success configuration. It warns about unreachable states, nonterminal dead ends, reserved suspend edges, missing terminal targets, and incompatible optional I/O declarations.], [Terminal targets require no node binding. Defaults are terminal states done and failed, with done successful.])
    ]
    #subsection(title: "Orchestrator configuration")[
      An orchestrator declares a set of operations and generation settings rather than an execution graph.
      #md-table(3, ([Option], [Default], [Meaning], [name and description], [Declared], [Identity and parent-visible metadata], [nodes], [Required], [Available action, agent, or explicit node specifications], [model], [nil], [ReqLLM model identifier], [system_prompt], [nil], [Instructions for model selection], [max_iterations], [10], [Loop safety limit], [temperature and max_tokens], [nil], [Provider defaults unless overridden], [stream], [false], [Collect streaming generation internally], [termination_tool], [nil], [Action for validated structured completion], [llm_opts and req_options], [Empty lists], [Generation options and opaque HTTP options], [max_tool_concurrency], [Unbounded], [Maximum executing calls per turn], [ambient and fork_fns], [Empty lists], [Context extraction and boundary transformations], [rejection_policy], [continue_siblings], [Effect of a rejected gated call], [hibernate_after], [Absent], [Enable checkpoint selection for long suspensions]))
      #points([Per-node requires_approval metadata is extracted into gated node names. Runtime approval_policy is evaluated for calls not already statically gated; it is not safely embedded as a closure in compile-time module attributes.], [configure accepts system_prompt, nodes, model, temperature, max_tokens, max_iterations, req_options, and conversation. It replaces supplied values; unknown keys raise ArgumentError.], [A node override rebuilds wrapped nodes, tool specifications, name_atoms, and schema_keys together. Termination action deduplication is re-applied; callers do not manually maintain internal maps.])
      #info(title: "Grounding")[A caller reads get_action_modules, filters that list by the caller's role, and supplies nodes to configure before query. This is a host policy step; it is not evidence that Composer authenticates the caller.]
    ]
  ])
  #section(title: "Node adapters", lead: "Every node receives its own struct, flattened context, and options. Optional callbacks describe runtime dispatch, tool metadata, and I/O expectations.", body: [
    #md-table(3, ([Callback], [Required], [Contract], [run/3], [Yes], [ok with result, ok with result and outcome, or error with reason], [name/1 and description/1], [Yes], [Instance-visible identifier and description], [to_directive/3], [No], [ok with directives and optional state effects], [to_tool_spec/1], [No], [Name, description, parameter_schema map or nil], [schema/1], [No], [Input schema or nil], [input_type/1 and output_type/1], [No], [map, text, object, or any]))
    #code-block("elixir", "run(node, context, opts) ->\n  {:ok, result} | {:ok, result, outcome} | {:error, reason}\nto_directive(node, flat_context, opts) ->\n  {:ok, directives} | {:ok, directives, side_effects}\n# side_effects is a keyword list applied by the strategy")
    #md-table(2, ([Directive option], [Purpose], [result_action], [Action atom routing execution results], [meta], [Call ID and tool name for ActionNode], [tag], [Parent-assigned child state or call identity], [structured_context], [Full Context value for child forking or parallel preparation], [tool_args], [Agent tool arguments merged into child input], [request_fields], [Flow-location enrichment for HumanNode], [fan_out_id], [Parallel operation correlation]))
    #points([A two-element ok result implies outcome ok. An error result implies outcome error; a three-element ok result carries its explicit outcome.], [Strategy dispatch is polymorphic through the node's to_directive callback. The strategy applies returned state effects, including pending suspension or FanOut state, before emitting directives.])
    #subsection(title: "Action and agent adapters")[
      #term("term-action-node") wraps a Jido Action; #term("term-agent-node") wraps an Agent with per-use execution configuration.
      #md-table(3, ([Adapter], [Configuration], [Dispatch], [ActionNode], [Action module and options], [Delegate metadata; emit RunInstruction], [AgentNode], [agent_module, mode, opts, signal_type, on_state], [Direct sync helper or SpawnAgent], [HumanNode], [Question and response policy], [Immediate suspend result], [DynamicAgentNode], [Registry and assembly_opts], [Assemble and execute a task]))
      #points([AgentNode defaults to sync. Direct run supports run_sync, query_sync, or the supported Jido AI ask_sync interface; async and streaming are not directly runnable and return an execution error.], [Runtime strategy dispatch may use SpawnAgent even for sync configuration. Async avoids blocking the parent; streaming permits selected upstream state notifications through on_state.], [FanOut and Map direct child execution calls run/3, so AgentNode children on that path must use sync. This limitation is part of the execution contract, not a failure of recursive composition.])
      #subsection(title: "Jido AI bridge")[
        The bridge supports the documented ask_sync interface without exposing internal agent state as a tool schema.
        #points([Detection requires ask_sync/3 and excludes modules exporting Composer run_sync/2 or query_sync/3. The bridge creates a temporary AgentServer, calls ask_sync, receives the result, and stops the server with a cleanup delay.], [The model sees a query string parameter. CoDAgent draft_sync, CoTAgent think_sync, and ToTAgent explore_sync are not detected by this interface.])
      ]
    ]
    #subsection(title: "Human input adapter")[
      #term("term-human-node") constructs a request without blocking the caller.
      #md-table(3, ([Field], [Default], [Meaning], [name and description], [Required], [Identifier and purpose], [prompt], [Required], [Static text or context-to-text function], [allowed_responses], [approved and rejected], [Permitted outcome atoms], [response_schema], [nil], [Optional structured response validation], [timeout], [infinity], [Wait duration in milliseconds], [timeout_outcome], [timeout], [Expiry outcome], [context_keys], [nil], [All keys unless a subset is selected], [metadata], [Empty map], [Notification metadata]))
      #points([The node evaluates its prompt, selects visible context, constructs ApprovalRequest, stores it under #raw("__approval_request__"), and returns ok with suspend. The strategy interprets the marker and owns waiting.], [In workflows, the human-input state and the guarded action are separate states. approved means the person approved, not that the guarded action succeeded.], [HumanNode.to_tool_spec returns nil, so direct LLM-tool exposure is unsupported. The source's advisory HumanNode tool remains an unresolved alternative, distinct from implemented mandatory approval gating.])
    ]
    #pagebreak()
    #subsection(title: "Parallel and traverse adapters")[
      #term("term-fan-out") runs named branches; #term("term-map-node") maps one child over a runtime collection.
      #md-table(3, ([Field], [FanOutNode], [MapNode], [name], [Required identifier], [Required identifier], [child selection], [Named branch/node pairs], [over key or key path and one node], [merge], [deep_merge or custom function], [Ordered results list], [timeout], [30,000 ms default; infinity allowed], [30,000 ms per element], [max_concurrency], [nil means unbounded], [nil means all], [on_error], [fail_fast or collect_partial], [fail_fast or collect_partial; fail_fast default]))
      #points([FanOut default merge scopes each result by branch name and deep-merges the resulting map. A custom merge receives branch-name/result pairs; collect_partial retains errors alongside successes for that merge.], [FanOutNode.to_tool_spec returns nil. It is not directly exposed as an LLM tool; an enclosing agent composition can provide a tool boundary.], [MapNode reads over at dispatch time. Its directive path merges map elements into base context and wraps other elements under item before merging. Direct run instead passes only the element map or item wrapper; the source's full-context intent remains pending for that path.], [MapNode preserves input order and returns results under results, subsequently scoped by the parent. Empty, missing, and non-list collections produce an empty results list without element dispatch.], [Both directive paths create FanOutBranch with child_node and params. Indexed Map branches use generated item identifiers; the executor calls the child node's run/3 uniformly.], [Backpressure queues excess branches and refills slots when results arrive. Fail-fast cancels running agent children through StopChild; MapNode collect_partial retains successful values and error tuples in input order.], [Nested traverse needs no special mechanism because MapNode is a node. Custom reduction belongs in a following ActionNode; streaming collections and element-transform callbacks remain outside the migrated scope.])
    ]
  ])
  #section(title: "Workflow strategy and runtime protocol", lead: "The strategy drives Machine operations and retains enough correlation state to interpret asynchronous results.", visual: sequence(
    title: "One workflow node", accent: "blue", participants: ((id: "strategy", label: "Strategy"), (id: "machine", label: "Machine"), (id: "runtime", label: "Runtime")),
    steps: (seq-msg("strategy", "machine", "current_node"), seq-msg("strategy", "runtime", "node-generated directive"), seq-msg("runtime", "strategy", "instruction result", dashed: true), seq-msg("strategy", "machine", "apply_result then transition"), seq-msg("machine", "strategy", "next state or terminal", dashed: true)),
    caption: [The returned instruction result is interpreted before the next directive is chosen. A suspend result takes the waiting path instead of transition lookup.],
  ), body: [
    #md-table(2, ([Strategy field], [Meaning], [machine], [Current Machine value], [module], [Owning strategy module], [error_reason], [Original failure or nil], [pending_child], [Tag/node pair or nil], [child_request_id], [Child correlation identifier or nil], [pending_suspension], [Active Suspension or nil], [fan_out], [Parallel collection state or nil], [children], [Serializable refs and phases], [#raw("_obs")], [Workflow observation state]))
    #md-table(2, ([Machine operation], [Contract], [new/1], [Initialize from options], [current_node/1], [Read the node bound to current state], [transition/2], [Return updated machine or transition error], [terminal?/1], [Test whether execution has ended], [apply_result/2], [Adapt and scope the accepted result]))
    #subsection(title: "Workflow signal routes")[
      Every listed signal maps to one strategy action; action results arrive as Jido.Instruction payloads rather than arbitrary tuples.
      #md-table(2, ([Signal], [Action], [composer.workflow.start], [workflow_start], [composer.workflow.child.result], [workflow_child_result], [jido.agent.child.started], [workflow_child_started], [jido.agent.child.exit], [workflow_child_exit], [composer.fan_out.branch_result], [fan_out_branch_result], [composer.suspend.resume], [suspend_resume], [composer.suspend.timeout], [suspend_timeout], [composer.child.hibernated], [child_hibernated]))
      #points([workflow_start initializes context and dispatches the initial node. workflow_node_result and workflow_child_result scope a result, extract its outcome, transition, and dispatch the next node.], [child_started registers lifecycle metadata in Children; child_exit handles unexpected termination or cleanup. Startup context is carried in SpawnAgent options; older narrative references to sending a second startup signal are not an additional required step.], [fan_out_branch_result stores a branch result and either dispatches queued work, waits for suspended work, or merges and transitions. child_hibernated records a paused ChildRef and checkpoint key.])
    ]
    #subsection(title: "Error preservation")[
      Failures retain their diagnostic value from the original node through nested callers.
      #md-table(3, ([Source error class], [Intended trigger], [Implemented class], [Validation], [Invalid DSL configuration, state references, or transition keys], [invalid], [Transition], [No matching state/outcome transition], [transition], [Execution], [Node or child operation failure], [execution], [Communication], [Delivery, timeout, or unexpected child exit], [communication], [Orchestration], [Generation, tool selection, or iteration failure], [orchestration]))
      #points([The source requires machine-readable error codes, human-readable messages, and diagnostic context identifying current state, node, and outcome. The intended mapping above preserves that obligation; it does not assert that every failure path constructs that class.], [Error implements Splode classes and constructors with messages and details. TransitionError adds state and outcome; ExecutionError adds node; the remaining constructors do not expose all three fields.], [Class atoms and exception modules identify implemented error kinds; the constructors do not declare a separate uniform code field. Ordinary RuntimeError directives and preserved underlying reasons also remain in use; uniform diagnostic coverage stays in the pending ledger.])
      #points([Capture error_reason from node and child errors, failed transitions, FanOut fail-fast, and failed timeout or resume transitions. Initialize it to nil on a fresh run.], [A successful error transition can route to a configured recovery state. A missing transition produces an Error directive; terminal failure exposes the captured reason.], [The DSL reads error_reason with Map.get and uses workflow_failed only when the key is absent. An existing nil value remains nil; the source's broader fallback wording is not implemented.], [Failure paths close the agent span and record the actual error. Direct-failure helpers set status, preserve the reason, and close the span together.], [Original errors survive checkpoints when serializable. A child workflow's returned reason becomes its parent's error_reason rather than an inspected string.])
    ]
  ])
  #section(title: "Orchestrator strategy and model boundary", lead: "The strategy manages turn state and tool resolution. LLMAction performs generation; AgentTool adapts node metadata and results.", body: [
    #subsection(title: "Turn state and routes")[
      Orchestration state contains configuration, accumulated conversation, and independent collections for executable, gated, and suspended calls.
      #md-table(2, ([State group], [Fields], [Generation configuration], [model, system_prompt, temperature, max_tokens, stream, llm_opts, req_options], [Operation configuration], [nodes, tools, termination_tool_name, termination_tool_mod], [Progress], [status, iteration, max_iterations, conversation, result], [Call tracking], [tool_concurrency, approval_gate, suspended_calls], [Composition state], [context, ambient_keys, children, pending_suspension, hibernate_after, #raw("_obs")]))
      #md-table(2, ([Signal], [Action], [composer.orchestrator.query], [orchestrator_start], [composer.orchestrator.child.result], [orchestrator_child_result], [jido.agent.child.started], [orchestrator_child_started], [jido.agent.child.exit], [orchestrator_child_exit], [composer.suspend.resume], [suspend_resume], [composer.suspend.timeout], [suspend_timeout], [composer.child.hibernated], [child_hibernated]))
      #points([orchestrator_start seeds context and conversation, then emits RunInstruction for LLMAction. orchestrator_llm_result completes, fails, or dispatches selected calls.], [Action calls return through orchestrator_tool_result; agent calls return through orchestrator_child_result. Each normalized result carries id, name, and result.], [ToolConcurrency contains pending, completed, queued, and max_concurrency. StatusComputer combines it with gated calls and suspended calls before allowing another model turn.], [Context splits declared ambient keys from input and inherits the reserved ambient marker at child boundaries. Action nodes see a flat map; agent nodes receive forked context. Raw ambient values are not inserted into model messages.])
      #subsection(title: "Tool queue capacity")[
        ToolConcurrency retains call IDs awaiting results, completed result records, and queued call data independently.
        #md-table(2, ([Operation or field], [Observed contract], [max_concurrency], [nil is unbounded; otherwise limits executing calls], [max_queue_depth], [nil is unbounded; otherwise limits enqueue/2], [enqueue/2], [Returns ok with updated state or error with queue_full at the limit], [drain_queue/1], [Moves queued calls into free slots and returns those calls for dispatch], [dispatch/3], [Replaces pending and queued collections and clears completed results]))
        #points([max_queue_depth belongs to ToolConcurrency.new options, not to the public orchestrator DSL or configure options. Strategy initialization supplies max_concurrency only.], [The bound is checked by enqueue, not by dispatch's initial queue assignment. When an approved call cannot be enqueued, the strategy removes its gate entry and records a tool-error result rather than running it.])
      ]
    ]
    #pagebreak()
    #subsection(title: "AgentTool boundary")[
      #term("term-agent-tool") converts node descriptions into model-facing tool specifications.
      #md-table(2, ([Operation], [Result], [to_tool(node)], [ReqLLM.Tool from node name, description, and schema], [to_context(tool_call)], [Argument map suitable for node execution], [to_tool_result(call_id, name, result)], [Correlated normalized result for the next turn]))
      #points([NimbleOptions and Zoi schemas are converted into JSON Schema. The ReqLLM tool carries a no-op callback because Composer dispatches execution externally.], [Call arguments are parsed maps. The call ID is retained independently of the tool name; repeated calls can share a tool name but must still correlate individually.], [name_atoms and schema_keys are derived from configured operations. The migration does not add a new dynamic atom-conversion policy beyond the existing documented maps.])
    ]
    #subsection(title: "LLMAction boundary")[
      #term("term-llm-action") calls ReqLLM directly; no separate provider facade or configurable LLM behavior is introduced.
      #sequence(title: "Generation and tool feedback", accent: "blue", participants: ((id: "s", label: "Strategy"), (id: "a", label: "LLMAction"), (id: "r", label: "ReqLLM")), steps: (seq-msg("s", "a", "conversation and flat options"), seq-msg("a", "r", "generate or collect stream"), seq-msg("r", "a", "response and context", dashed: true), seq-msg("a", "s", "classified answer or calls", dashed: true), seq-note("s", [Execute calls; pass their results to the next turn.])), caption: [Provider-specific message construction remains inside ReqLLM.])
      #points([The first call constructs a ReqLLM.Context from prompt and query. Later calls append tool results with ReqLLM.Context.tool_result; response context preserves assistant messages and mixed content.], [stream false uses generate_text/3. stream true uses stream_text/3 and collects internally before classification; it does not promise incremental strategy-level results.], [Instruction parameters are conversation, tool_results, tools, model, query, system_prompt, temperature, max_tokens, stream, llm_opts, and req_options. The action merges explicit generation settings into llm_opts and maps req_options to req_http_options.], [Response classification returns tool_calls, optionally with reasoning text, or final_answer. Reasoning accompanying tool calls may be logged or discarded; it does not change dispatch semantics.], [ReqLLM owns provider encoding, argument parsing, result formatting, and response context. Strategy state owns the retained conversation and supplies it to the next call.])
    ]
    #subsection(title: "Structured termination")[
      A termination action provides validated structured completion without adding a separate generation mode.
      #points([The action's metadata and schema become a tool visible to the model. Its name is registered for lookup, but it is not a regular node and does not receive ordinary context scoping or approval gating.], [The max-iterations guard runs first. The first termination call then takes precedence over regular sibling calls; siblings in that batch are dropped.], [The documented implementation executes the termination action through Jido.Exec.run inline. Success completes with NodeIO.object; failure becomes a model-facing error result and the loop continues.], [A consumer requiring approval around a sensitive termination action cannot assume ordinary gated-node metadata applies. Moving execution behind directives would be a design change, not part of this migration.])
    ]
    #subsection(title: "Failures and restoration")[
      Failure and restore paths preserve structured state rather than replacing it with display strings.
      #points([Generation failures and iteration exhaustion end the run. Tool errors may be presented to the model as results; explicit abort policies end execution.], [The final error remains structured in result for callers. Only LLM-facing text uses inspect-style formatting. Error paths close iteration and agent spans, including partition errors and abort_iteration rejection.], [Fresh init applies when no matching state exists or status is idle. Restore applies to matching non-idle strategy state and preserves conversation, pending calls, iteration, context, and results.], [Restore rebuilds nodes, tools, name maps, gated-node metadata, approval policy, maximum concurrency, and req_options from runtime configuration. The provenance of a runtime-only approval-policy closure after a restart remains a pending decision.])
    ]
  ])
  #section(title: "Suspension and approval protocols", lead: "A pause is a valid result requiring continuation. Its owner validates correlation and policy before accepting resumed work.", visual: sequence(
    title: "Human continuation", accent: "blue", participants: ((id: "s", label: "Strategy"), (id: "h", label: "Host notification"), (id: "p", label: "Person")), steps: (seq-msg("s", "h", "Suspend with request"), seq-msg("h", "p", "visible context and question"), seq-msg("p", "h", "decision and data"), seq-msg("h", "s", "generalized resume signal"), seq-note("s", [Validate ID, decision, and schema before advancing.])), caption: [The host owns delivery and respondent authentication. The record itself contains no authorization proof.]),
    body: [
      #points([Suspension reasons are human_input, rate_limit, async_completion, external_job, and custom. The record carries ID, created_at, resume_signal, timeout, timeout_outcome, metadata, and optional ApprovalRequest.], [Suspend carries suspension, notification configuration, and hibernate intent. SuspendForHuman is the compatibility constructor for human_input, not a separate lifecycle.], [ApprovalRequest contains ID, prompt, visible_context, allowed_responses, response_schema, timeout, timeout_outcome, metadata, and created_at. Strategy enrichment adds agent_id, agent_module, workflow_state or tool_call, and node_name.], [ApprovalResponse contains request_id, decision, data, respondent, comment, and responded_at. The strategy validates identity, allowed decision, and data schema before recording hitl_response in context.])
      #subsection(title: "Workflow pause and resume")[
        The workflow keeps its Machine at the current state while its strategy waits.
        #points([Extract #raw("__suspension__") or legacy #raw("__approval_request__"). Wrap a legacy request as human_input, enrich its flow location, merge remaining result data, store pending_suspension, and set waiting.], [Emit Suspend and an optional Schedule timeout. A qualifying long pause can additionally emit CheckpointAndStop.], [Resume validates the pending ID. Human input performs request-specific validation; other reasons use outcome and data from the signal. Accepted data is merged, pending state is cleared, and the selected outcome advances the Machine.], [An active timeout consumes timeout_outcome, defaulting to timeout. A timeout for an already-resolved suspension is a no-op.])
      ]
      #subsection(title: "Approval gate and sibling policy")[
        The gate partitions model-selected calls before their ordinary execution.
        #md-table(2, ([Rejection policy], [Effect], [continue_siblings], [Let running calls finish and return all results to the model], [cancel_siblings], [Stop running child calls and synthesize cancellation results], [abort_iteration], [Cancel remaining work and fail the run]))
        #points([Static requires_approval and dynamic approval_policy both feed the partition. Static membership gates without calling the dynamic policy; otherwise only the exact atom require_approval gates.], [A tuple such as require_approval with options is not accepted as a gating result and proceeds ungated. This compatibility limitation is not a recommended policy return.], [A held call receives an approval request; ungated calls need not wait. Rejection produces a synthetic tool result explaining the refusal; unless the policy aborts, the model may choose a different approach or return a final answer.], [Status is awaiting_tools_and_approval while siblings execute, then awaiting_approval when only held decisions remain. All required collections must resolve before the next turn; mixed approval/suspension labels follow the core lifecycle chapter's observed precedence.])
      ]
      #subsection(title: "General tool suspension")[
        A tool can suspend without human approval, such as while awaiting a rate limit or external operation.
        #points([Detection accepts a direct suspend status or an ok status carrying suspend in effects. The strategy extracts or constructs Suspension, removes the call from pending, stores suspension plus call under suspended_calls[id], and emits Suspend.], [Resume with data accepts that data as the result without executing the tool again. Resume without data re-dispatches the call; both remove the old suspension entry. Unknown IDs produce an Error directive in the documented orchestrator path.], [An active timeout becomes an error tool result and removes the entry. Once pending, gated, and suspended collections resolve, the next model turn receives all collected results.])
      ]
      #subsection(title: "Parallel and nested pauses")[
        Parent waiting does not transfer ownership of a child's approval decision.
        #points([FanOut tracks queued, executing, completed, and suspended branches independently. When running work finishes and only suspensions remain, it emits Suspend for each unresolved branch. Resumed results join completed_results before final merge.], [An outer workflow waiting for InnerOrchestrator remains waiting while the child handles ResearchAgent and a gated DangerousAction. Research can finish before approval; the outer workflow sees only the child's eventual result or error.], [Independent children can hold distinct approval requests concurrently. A sequential Machine has one current state, but that state can contain parallel children with separate requests.], [Inner and outer timeouts are independent. If an outer timeout stops a child first, the host should mark the corresponding external request cancelled; the source does not define a durable notification protocol for that cancellation.], [A response arriving during checkpoint transition must be queued by the host for post-restore delivery. The strategies ignore resolved timeouts but emit Error directives for unmatched resumes; the external Resume helper instead returns no_matching_suspension.])
      ]
    ])
  #section(title: "Checkpointing and resumption", lead: "Durable checkpoints retain logical execution state while runtime handles and observation spans are reconstructed or reset.", body: [
    #md-table(3, ([Mode], [Trigger], [Effect], [Live wait], [Suspension begins], [Process and full heap remain], [Hibernate intent], [Suspend.hibernate true or after setting], [Current documented integration logs intent; memory unchanged], [Checkpoint and stop], [Suspension timeout meets hibernate_after threshold], [Persist state, notify parent, stop process]))
    #points([The detailed persistence contract describes threshold selection from suspension timeout, not a guaranteed elapsed-time timer. Older narrative says the threshold fires; that wording must not imply a scheduler that is not defined.], [CheckpointAndStop resolves storage from its directive or agent lifecycle configuration, persists through Jido.Persist.hibernate, emits composer.child.hibernated, and returns a stop tuple. checkpoint_data is reserved and currently described as unread.], [The runtime accepts ok, async, and stop directive-executor returns. The legacy OTP-hibernate proposal would require either a new return variant or a passive AgentServer option; neither is claimed available.])
    #warning(title: "Stopping does not prove a checkpoint exists")[CheckpointAndStop logs missing storage or persistence failure, then continues to parent notification when a parent PID exists and returns the hibernated stop tuple. A notification therefore does not prove recoverability. This observed behavior remains a safety limitation, not approval to discard state after failed persistence.]
    #subsection(title: "Checkpoint data and serialization")[
      Jido's default agent checkpoint and Composer's optional strategy preparation are separate paths.
      #md-table(3, ([Field or marker], [Location], [Observed behavior], [version], [Base checkpoint], [1], [agent_module and id], [Base checkpoint], [Restorable agent identity], [state], [Base checkpoint], [Includes #raw("__strategy__")], [thread], [Added by Jido.Persist], [Thread ID and revision or nil; thread content is stored separately], [children], [Strategy state], [Child references and phases], [checkpoint_status], [Strategy state after Composer preparation], [Set to hibernated only when absent], [checkpoint_schema], [Source-intended checkpoint field], [Not inserted by the default callback or Composer preparation; schema_version/0 separately returns composer_v1], [Claim status], [Optional host storage callback], [Not a default top-level checkpoint field]))
      #points([The preservation requirement covers Machine state, context, history, conversation, iteration, pending suspensions, parallel results, queued branches, gated calls, and suspended calls. The default callback copies agent state; it does not invoke the strategy's prepare_for_checkpoint hook.], [Explicit Composer preparation delegates to strip_for_checkpoint, resets Obs, and removes supported top-level functions and the nested approval policy. It also inserts checkpoint_status; callers must not infer that Jido.Persist.hibernate or CheckpointAndStop performs this step automatically.], [The current storage format is compressed Erlang term serialization. JSON and MsgPack are possible future export formats, not equivalent supported persistence promises.], [The source requires stripping #raw("__parent__.pid") while preserving id, tag, and meta. The observed default callback retains that PID; Composer's strategy-only preparation cannot remove it from the containing agent state.], [Span handles and arbitrary nested custom closures are not proven checkpoint-safe. Safe parent stripping and automatic transient-state cleanup remain requirements in the pending ledger, not completed guarantees.], [Fork transformations use MFA tuples to remain serializable. Restore rebuilds configured nodes and policies from strategy options; a runtime-only policy without a durable reconstruction source can be lost.])
    ]
    #subsection(title: "Nested checkpoint and restore order")[
      Checkpointing proceeds from child to parent; restoring an inactive tree proceeds from parent to child.
      #sequence(title: "Nested checkpoint and restore", accent: "blue", participants: ((id: "p", label: "Parent"), (id: "c", label: "Child"), (id: "s", label: "Storage")), steps: (seq-msg("c", "s", "save checkpoint"), seq-msg("c", "p", "checkpoint key; then stop"), seq-msg("p", "s", "save parent if required"), seq-msg("s", "p", "restore parent", dashed: true), seq-msg("p", "c", "spawn from child checkpoint"), seq-msg("p", "c", "deliver addressed continuation")), caption: [A live parent need not be restored again. Targeted resume addresses the suspended agent; fresh parent links are needed when the enclosing tree was stopped.])
      #points([The parent records the child's checkpoint key and paused status before its own checkpoint. ChildRef retains agent module, agent ID, tag, suspension ID, checkpoint key, status, and phase.], [The source's parent-first restore order is a host integration responsibility. Resume does not discover the outer tree or start AgentServer; it returns paused-child SpawnAgent directives after the directives produced by delivery.])
      #code-block("elixir", "Resume.resume(agent_or_nil, suspension_id, resume_data, opts)\n  -> {:ok, resumed_agent, directives} | {:error, reason}\n# Required: deliver_fn: fn agent, {:suspend_resume, params} ->\n#   {updated_agent, directives}\n# For nil agent: thaw_fn: fn agent_id -> {:ok, agent} | {:error, reason}\n#               agent_id: id\n# Optional: storage: %{compare_and_set_status: fn id, from, to -> result end}")
      #points([The helper accepts an existing Jido.Agent value, or calls thaw_fn with agent_id when that value is nil. Registry lookup, storage selection, and process startup belong to caller-supplied integration.], [deliver_fn receives a strategy-command tuple, not a Jido.Signal. A host targeting AgentServer translates it to the composer.suspend.resume route and owns delivery.], [Matching checks cover pending_suspension, suspended_calls, and suspended FanOut branches. ApprovalGate entries are handled by the orchestrator's resume route but are not matched by this external helper.], [Missing agent resolution returns agent_not_available; no matching suspension returns no_matching_suspension. Successful helper delivery returns the agent and directives; an Error directive from the strategy is not automatically converted into a helper error tuple.])
    ]
    #pagebreak()
    #subsection(title: "Resume claim and replay")[
      Optional host storage can claim delivery after the helper has resolved or thawed the agent.
      #state-machine(title: "Checkpoint claim", accent: "blue", initial: "hibernated", accepting: ("resumed",), states: ("hibernated", "resuming", "resumed"), transitions: (("hibernated", "resuming", "host CAS after resolution"), ("resuming", "resumed", "host CAS after delivery")), caption: [This is the permitted status-transition graph, not proof that both writes succeed. The source requires competing claims to be refused; the host's callback supplies that atomicity and its error. Without storage, Resume skips both claim calls.])
      #warning(title: "Claims do not establish replay safety")[Thaw occurs before the first claim. A failed delivery has no claim rollback, and failure of the final claim update is ignored while Resume returns its success tuple. Repeated effects, stranded claims, and recovery from interrupted delivery remain unresolved safety requirements.]
      #md-table(2, ([Persisted condition], [Replay], [Child phase spawning], [Re-emit SpawnAgent], [Child phase awaiting_result], [Keep waiting], [Orchestrator awaiting_llm], [Re-emit model call from conversation], [awaiting_tools or legacy awaiting_tool], [Re-dispatch pending calls], [awaiting_tools_and_approval], [Replay pending calls; gated calls remain held], [awaiting_tools_and_suspension], [Replay pending calls; suspended calls retain resume path]))
      #points([Checkpoint.replay_directives combines child phase replay with the strategy's replay_directives_from_state callback. For a Children struct, no spawning tags triggers fallback to ChildRef.phase even when the phases map is nonempty; the legacy flat-map path falls back only when child_phases is empty.], [A stale spawning phase on ChildRef can therefore re-emit SpawnAgent despite another phase in Children.phases. This observed compatibility precedence is not a promise of duplicate-free replay.], [Resume prepends replay directives when checkpoint_status is present, then appends delivery directives and paused-child respawns. The default checkpoint path does not add that marker; callers must explicitly arrange the required preparation.], [In-flight HTTP and signals are not durable. Repeated dispatch can repeat external effects unless the host or operation enforces idempotency.], [New fields obtain restore defaults; removed fields are ignored. Changed state graphs require the agent's restore callback to map old states. If a required module was renamed or removed, restore fails with a clear error until an explicit migration is supplied.], [Schedule timers do not survive process death. The host must find expired suspensions using created_at and timeout, address live or checkpointed agents, and mark missing checkpoints expired.])
    ]
  ])
  #section(title: "Skill assembly and dynamic delegation", lead: "A capability bundle becomes an ordinary orchestrator configuration before the caller chooses how to execute it.", body: [
    #sequence(title: "Assembly without execution", accent: "blue", participants: ((id: "caller", label: "Caller"), (id: "assemble", label: "Skill.assemble"), (id: "agent", label: "Orchestrator")), steps: (seq-msg("caller", "assemble", "skills and options"), seq-msg("assemble", "agent", "configure prompt and tool union"), seq-msg("agent", "caller", "inspectable agent", dashed: true)), caption: [No model call is required to inspect the assembled prompt and operations.])
    #points([Skill fields are name, description, prompt_fragment, and tools. Tool modules follow the same action/agent wrapping rules as orchestrator nodes, including workflow, orchestrator, and supported Jido AI agents.], [assemble combines base_prompt, a Capabilities heading, and selected prompt fragments in order. It deduplicates tool modules and uses ordinary orchestrator configuration to instantiate the agent.], [Assembly options include base_prompt, model, and max_iterations with default 10; additional generation and HTTP options pass through configure where supported. Prompt concatenation does not infer fragment dependencies or remove semantic duplication.], [DynamicAgentNode stores name, description, skill_registry, and assembly_opts. It exposes task text and skill-name list, looks up selected skills, assembles an agent, calls query_sync, and returns the result.], [A workflow may call assembly separately and inspect its product before execution. Predefined specialists remain appropriate for stable configurations; runtime assembly serves combinations selected from a larger capability set.], [The registry is an inline list. Module registries, external discovery, a custom prompt composer, and a Jido AI Skill adapter remain extensions, not promised current behavior.])
    #code-block("elixir", "Skill.assemble(skills, opts) -> {:ok, agent} | {:error, reason}\nDynamicAgentNode.run(node, context, opts)\n  -> {:ok, result} | {:error, reason}")
    #points([Skill.assemble rejects unknown options with an ArgumentError inside an error tuple; it does not raise that validation error.], [DynamicAgentNode resolves skill names in requested order and returns an error naming the first absent skill. Assembly errors and query errors propagate; a suspended child query becomes an error containing the suspension rather than a resumable node suspension.], [DynamicAgentNode.to_directive merges tool_args over flat context and emits RunInstruction for ExecuteAction, retaining result_action and meta. ExecuteAction invokes run/3 and wraps success under result; direct run returns the unwrapped result.])
    #info(title: "Grounding")[Selecting web_search and planning combines their instructions and deduplicates shared tools. DynamicAgentNode keeps model and base_prompt inside assembly_opts; the older use-case sketch placing those fields directly on the node is not its canonical configuration.]
  ])
  #section(title: "Observation and diagnostics", lead: "Observation records execution evidence without granting authority over results, approvals, or workflow transitions.", body: [
    #diagram(altitude: "L3", title: "Observation ownership", accent: "blue", nodes: ((id: "strategy", label: "Strategy"), (id: "obs", label: "Obs"), (id: "observe", label: "Jido.Observe", external: true), (id: "tracer", label: "Optional tracer", external: true), (id: "otel", label: "OpenTelemetry", external: true)), edges: (("strategy", "obs", "update span state"), ("obs", "observe", "start or finish"), ("observe", "tracer", "callback"), ("tracer", "otel", "translate")), caption: [Obs tracks values; Jido.Observe and OtelCtx perform instrumentation effects. Optional OpenTelemetry absence is a deliberate no-op, not a failed business operation.])
    #md-table(3, ([Span], [Start], [Finish], [Agent], [Workflow or orchestrator start], [Terminal success or error], [Iteration], [Before model call], [All tool results, final answer, or error], [LLM], [Before generation directive], [Model result], [Tool or node], [Dispatch], [Node or child result], [Parallel branch], [Child branch execution], [Child return]))
    #points([Telemetry prefixes share jido, composer and then agent, iteration, llm, or tool. Workflow nodes also use tool so one tracer mapping covers both composition patterns.], [Orchestrator.Obs retains agent_span, llm_span, tool_spans, iteration_span, and cumulative_tokens. Workflow.Obs retains agent_span and node_span.], [Jido.Observe.start_span emits start and returns opaque context; finish_span emits stop with duration; finish_span_error emits exception. A pluggable tracer receives callbacks.], [AgentObs.JidoTracer maps agent, llm, and tool directly and iteration to chain, then uses the Phoenix translator for OpenInference attributes.])
    #subsection(title: "Nesting and sibling isolation")[
      Child spans must inherit the caller's tool span without making sibling calls appear nested.
      #points([Save the previous OTel context, start each tool span, capture its context by call ID, and restore the previous context. Pass the captured value through SpawnAgent.meta.otel_parent_ctx.], [The synchronous driver attaches it with OtelCtx.with_parent_context around child execution. A child workflow can reattach parent metadata before opening its agent span. Parallel tasks capture before spawn and attach inside each task.], [with_parent_context restores through try/after. get_current returns nil and attach does nothing if OpenTelemetry.Ctx is unavailable.])
    ]
    #subsection(title: "Measurements and checkpoint hygiene")[
      Measurements describe execution outcomes and are reset where their runtime references cannot persist.
      #md-table(2, ([Span], [Measurements], [Agent], [result, status, iterations, cumulative prompt/completion/total tokens, error], [LLM], [token usage, finish_reason, normalized output messages], [Tool], [tool_name, result, ok or error status, error], [Iteration], [Outcome summary or error]))
      #subsection(title: "MapNode observation requirements")[
        The traverse source requires one parent node span for MapNode and child operations for its element executions.
        #md-table(2, ([Required observation], [Purpose], [Element count], [Size of the selected collection], [Concurrency], [Parallel execution setting], [Completion status], [Whether collection completed or failed], [Parent and child spans], [Relate the collection to each element execution]))
        #points([The observed workflow path opens the ordinary node span; MapNode's direct task path captures and reattaches OTel context for element work. These mechanisms do not establish that all required measurements are emitted.], [The inspected MapNode and workflow observation code does not emit explicit element-count and concurrency measurements for the collection span. The full source requirement is preserved in the pending ledger rather than removed or claimed complete.])
      ]
      #points([NodeIO is unwrapped for output measurements. The reserved tuple ambient marker is removed from tool arguments, child results entering the LLM, and workflow result measurements because those encoders cannot represent it.], [Explicit Composer checkpoint preparation resets Obs; the default persistence path does not guarantee that reset. Snapshot exposes status, done?, result, and details without requiring callers to inspect strategy internals.], [A paused snapshot can expose request_id, node_name, reason, and waiting_since. These are diagnostic data, not a substitute for validating the addressed resume.])
    ]
  ])
  #section(title: "Applied design and host responsibilities", lead: "The existing design selects an Elixir library and delegates runtime mechanisms to established Jido and ReqLLM boundaries.", body: [
    #md-table(3, ([Concern], [Applied choice], [Owner and consequence], [Language and runtime], [Elixir on BEAM], [Consumer library; immutable values and OTP process integration], [Agents and effects], [jido, jido_action, jido_signal], [Jido owns AgentServer, instructions, directives, and signals], [Model providers], [req_llm over Req], [LLMAction calls the provider-independent integration directly], [Schemas], [Zoi; legacy NimbleOptions], [Node and DSL validation; AgentTool JSON Schema conversion], [Errors], [Splode], [Validation, transition, execution, communication, orchestration classes], [Accumulation], [deep_merge], [Composition layer scopes results before merging], [Serialization], [Erlang terms; Jason for JSON], [Persist storage and model-facing schema/result boundaries], [Observation], [telemetry and optional OTel], [Jido.Observe, Obs, OtelCtx, and host tracer], [Provider tests], [ReqCassette and Req.Test], [Test-owned HTTP interception], [Checkpoint storage], [Jido.Persist and configured adapter], [Host supplies backend and verifies atomic claim support]))
    #points([The extracted decisions are #adr(1), #adr(2), #adr(3), and #adr(4). They preserve source rationale; they do not select new versions or claim current provider availability.], [The library is not a Phoenix application and does not mandate a database. Durable timeout scheduling, storage retention, notification retries, and credential management belong to the host integration.], [Prompt management consists of the declared system prompt, runtime override, and Skill fragments. Retrieval-augmented generation and MCP are not specified as built-in subsystems; ordinary nodes may wrap such capabilities.], [Approval and RBAC filtering require host identity and authorization. The documents do not specify authentication for resume, encryption, retention duration, sensitive-result redaction, or model-input injection defenses; callers must not infer those guarantees.], [Jido.Exec.Chain is a single-process linear action pipeline with shallow merge. Composer adds outcome graphs, agent composition, and scoped accumulation; Jido.Plan is a dependency DAG, while Workflow is an event-driven FSM with explicit parallel nodes.])
  ])
  #section(title: "Testing contracts", lead: "Pure model tests, deterministic directive loops, and recorded provider traffic test different boundaries.", body: [
    #md-table(3, ([Layer], [Target], [Evidence], [Unit], [Machine, merge, node construction, AgentTool, Error], [Direct input/output assertions], [Strategy], [Dispatch, concurrency, approval, replay], [LLMStub or manually driven directives], [Integration], [Nesting, branching, result adaptation], [Deterministic stub or cassette], [End-to-end], [Provider round trips and multi-turn composition], [Recorded HTTP cassette], [Recording], [Capture real provider response shape], [Explicit network run with secret filtering]))
    #points([LLMStub direct mode uses setup plus execute for a manually driven directive loop. Plug mode uses setup_req_stub and Req.Test so the real LLMAction and ReqLLM path still executes. Stub outcomes are tool_calls, final_answer, and error.], [ReqCassette record mode records when absent and replays when present; replay mode refuses missing cassettes; bypass always reaches the network. Never hand-author a cassette presented as recorded traffic.], [req_options carries the test plug through the strategy and LLMAction into req_http_options. Production logic does not inspect test mode.], [Central cassette filters remove authorization, x-api-key, cookie, set-cookie, provider key patterns, JSON api_key values, and Bearer tokens. Filters reduce exposure but do not prove arbitrary bodies are safe to publish.], [Test linear, branching, error, and nested workflows; single and multiple tool turns; agent tools; orchestrator-to-workflow composition; model errors; approval, suspension, checkpoint replay, and span cleanup.], [The source's development sequence is test-first: observe a failing contract test, implement, refactor, then exercise integration and the repository quality gate. This migration executes the document gate, not these implementation tests.])
  ])
  #section(title: "End-to-end walkthrough", lead: "The ETL example is the canonical executable-shape illustration. The remaining source scenarios show how the same boundary composes at other scales.", body: [
    #code-block("elixir", "use Jido.Composer.Workflow,\n  name: \"etl_pipeline\",\n  description: \"Extract, transform, validate, and load data\",\n  nodes: %{extract: ExtractFromAPI, transform: NormalizeSchema,\n    validate: ValidateRecords, load: WriteToStore,\n    quarantine: QuarantineBadRecords},\n  transitions: %{{:extract, :ok} => :transform,\n    {:transform, :ok} => :validate, {:validate, :ok} => :load,\n    {:validate, :invalid} => :quarantine, {:load, :ok} => :done,\n    {:quarantine, :ok} => :done, {:_, :error} => :failed},\n  initial: :extract")
    #code-block("elixir", "# Put the declaration above inside defmodule ETLPipeline.\nagent = ETLPipeline.new()\nETLPipeline.run_sync(agent, %{source: \"records\"})\n# Representative success, assuming the supplied actions return these maps:\n# {:ok, %{source: \"records\", extract: %{records: [1, 2]},\n#   transform: %{records: [1, 2]}, validate: %{valid: true},\n#   load: %{count: 2}}}")
    #points([This is a configuration example, not a runnable application: the named action modules are supplied by the consumer. The original names are preserved as quoted example identifiers.], [Each successful node result accumulates in its state scope. validate's invalid outcome selects quarantine; error uses the wildcard failed edge.], [An orchestrator may expose this workflow as a tool using AgentNode. The declared description tells the model when to choose it; the parent does not inspect the ETL transition table.])
    #md-table(3, ([Source scenario], [Composition], [What it demonstrates], [ETL pipeline], [Workflow with actions], [Fixed sequence and validation branch], [Research coordinator], [Orchestrator with search and query tools], [Runtime operation selection], [Project manager], [Orchestrator over onboarding, deploy, and report workflows], [Adaptive selection of fixed pipelines], [Content publisher], [Workflow with editorial orchestrator], [One adaptive step inside a fixed process], [Customer support], [Orchestrator to workflow to diagnostic orchestrator], [Three-level nesting], [Due diligence], [Workflow with financial, legal, and background branches], [Named parallel results before a final decision], [Product development], [Coordinator over specialist orchestrators], [Stable specialist boundaries], [Dynamic assembly], [Orchestrator with DynamicAgentNode and Skills], [Runtime capability selection]))
    #points([The editorial example requires a concrete mapping from structured verdict to workflow outcome; a prompt alone does not establish that adapter. Preserve it as an illustrative scenario until that mapping is specified.], [The due-diligence example uses named branch pairs in the canonical FanOut contract; its older unnamed branch-list sketch is not the constructor reference.], [For dynamic assembly, put model and base_prompt inside assembly_opts. The example's registry must actually contain every skill name the parent can select.], [The original detailed examples remain available in use-cases.md during review; their behavioral gaps are not silently presented as working code.])
  ])
]
