#let terms = (
  (slug: "term-node", title: [Node], body: [A configured participant with a context-in, result-out interface and an optional transition outcome.]),
  (slug: "term-context", title: [Context], body: [The data available to a composition, partitioned into ambient values, accumulated working results, and boundary transformations.]),
  (slug: "term-ambient", title: [Ambient context], body: [Read-only values inherited by a composition and its descendants.]),
  (slug: "term-working", title: [Working context], body: [The portion of context containing input data and results accumulated under node-specific scope keys.]),
  (slug: "term-fork-function", title: [Fork function], body: [A named module-function-arguments transformation that derives a child's ambient context at an agent boundary.]),
  (slug: "term-outcome", title: [Outcome], body: [An atom associated with a node result that determines a workflow transition. The reserved suspend outcome holds the current state instead.]),
  (slug: "term-node-io", title: [NodeIO], body: [An output envelope containing a map, text, or structured object with its type and optional schema.]),
  (slug: "term-workflow", title: [Workflow], body: [A composition whose declared states and outcome-driven transitions determine execution order.]),
  (slug: "term-machine", title: [Machine], body: [The workflow value containing configuration, current state, context, and transition history.]),
  (slug: "term-terminal-state", title: [Terminal state], body: [A declared workflow state that ends execution without running a node. Success states are the subset denoting successful completion.]),
  (slug: "term-orchestrator", title: [Orchestrator], body: [A composition whose language model selects calls to available nodes until it returns an answer or reaches a limit.]),
  (slug: "term-tool", title: [Tool], body: [The language-model-facing description of a callable node, including its name, description, and parameter schema.]),
  (slug: "term-tool-call", title: [Tool call], body: [A model-selected invocation identified by a call ID, tool name, and argument map.]),
  (slug: "term-suspension", title: [Suspension], body: [The serializable record of a paused computation and its resume correlation, reason, and timeout policy.]),
  (slug: "term-approval-request", title: [ApprovalRequest], body: [A serializable request for a human decision, with permitted outcomes and the context visible to the respondent.]),
  (slug: "term-approval-response", title: [ApprovalResponse], body: [A response to one approval request containing a decision, optional data, respondent information, and response time.]),
  (slug: "term-approval-gate", title: [Approval gate], body: [The policy and pending-call state that withhold selected tool invocations until human approval. _Avoid_: HumanNode — a separate human-input participant rather than enforcement around another invocation.]),
  (slug: "term-fan-out", title: [FanOutNode], body: [A node composing a fixed collection of named child nodes into one merged result.]),
  (slug: "term-map-node", title: [MapNode], body: [A node applying one configured child node to a runtime list and collecting results in input order.]),
  (slug: "term-traverse", title: [Traverse], body: [The composition operation that applies the same node to each element of a collection. _Avoid_: parallel — parallel composition selects a fixed set of different branches.]),
  (slug: "term-skill", title: [Skill], body: [A named capability bundle containing a description, prompt fragment, and compatible tool modules.]),
  (slug: "term-skill-assembly", title: [Skill assembly], body: [The transformation of selected skills and options into a configured orchestrator, independently of execution.]),
  (slug: "term-child-ref", title: [ChildRef], body: [A serializable reference to a child agent's identity, checkpoint, execution status, and communication phase.]),
  (slug: "term-snapshot", title: [Snapshot], body: [A strategy-independent view of execution status, completion, result, and diagnostic details.]),
)
